### PR TITLE
Maryann

### PR DESCRIPTION
**Pull request by mary-ruguru**
added the bidhistory component, the bidhistory jsx code and bidhistory css code , and also updated the App.jsx file by adding the routes.

### CODE REVIEW

**Comment by mary-ruguru** [comment]
I had conflicting files

**Comment by mary-ruguru** [comment]
conflicting files

**Comment by sereyatiampati** [comment]
There is still conflicting files.

**Comment by mary-ruguru** [comment]
merging conflicts

**Comment by mary-ruguru** [comment]
conflicting files

**Pull request merged**
